name: Test Jekyll Build

on:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

permissions: {}

jobs:
  #### TEST THAT THE GH PAGES SITE GETS BUILT WITHOUT ERRORS ####
  test:
    name: "Test GHPages site"
    if: github.repository == 'WordPress/Requests'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          # Use the version as per https://pages.github.com/versions/.
          ruby-version: 3.3.4
          bundler-cache: true

      - name: Test building the GH Pages site
        run: bundle exec jekyll build
